version: '3'
services:
  app:
    build: .
    image: creditsale:latest
    container_name: app
    ports:
      - "3000:7045"
    environment:
      - TZ='Asia/Tashkent'
    restart: always
    networks:
      - creditsale

networks:
  creditsale:
    external: true
